spring:
  application:
    name: wxshop
  datasource:
    url: jdbc:mysql://192.168.187.130:3306/wxshop?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf-8
    username: root
    password: my-secret-pw
    driverClassName: com.mysql.cj.jdbc.Driver
mybatis:
  config-location: classpath:db/mybatis/mybatis-config.xml

wxshop:
  redis:
    host: 192.168.187.130
    port: 6379
server:
  port:  8081
