spring:
  application:
    name: wxshop
  datasource:
    url: jdbc:mysql://localhost:3306/wxshop?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf-8
    username: root
    password: my-secret-pw
    driverClassName: com.mysql.cj.jdbc.Driver
mybatis:
  config-location: classpath:db/mybatis/mybatis-config.xml

wxshop:
  redis:
    host: localhost
    port: 6379
server:
  port:  8081
