spring:
  application:
    name: wxshop-order
  datasource:
    url: jdbc:mysql://localhost:3306/wxorder?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf-8&nullCatalogMeansCurrent=true
    username: root
    password: my-secret-pw
    driverClassName: com.mysql.cj.jdbc.Driver
wxshop:
  orderservice:
    version: 0.0.1
    url: ""

server:
  port: 8081

mybatis:
  config-location: classpath:db/mybatis/mybatis-config.xml

dubbo:
  config-center:
    timeout: 10000
  metadata-report:
      timeout: 10000
  registry:
    address: zookeeper://localhost:2181
  scan:
    base-packages: com.soohea.order.service
